name: Build Windows Executable

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6>=6.4.0
        pip install openpyxl>=3.1.0
        pip install pyinstaller

    - name: Build Windows executable
      run: |
        pyinstaller --name="УчебныйГрафик" --onefile --windowed --noconsole --icon=icon.ico main.py

    - name: Create distribution package
      run: |
        mkdir УчебныйГрафик_v1.0
        copy dist\УчебныйГрафик.exe УчебныйГрафик_v1.0\
      shell: cmd

    - name: Create README file
      run: |
        @"
        # Учебный график - Инструкция

        ## Запуск приложения
        Дважды кликните на УчебныйГрафик.exe

        ## Быстрый старт
        1. Выберите тип программы и начальный год
        2. Нажмите 'Пример ординатуры' для загрузки примера
        3. Или добавьте периоды вручную
        4. Нажмите 'Сгенерировать график'
        5. Нажмите 'Скачать Excel'

        ## Типы занятий
        Т - Теоретическая подготовка
        П - Практика
        ПА - Промежуточная аттестация
        ГИА - Государственная итоговая аттестация
        К - Каникулы

        ## Разработчики
        Бахмутов Е., Клюев П.

        Версия: 1.0 (2025)
        "@ | Out-File -FilePath "УчебныйГрафик_v1.0\README.txt" -Encoding UTF8
      shell: pwsh

    - name: Create ZIP archive
      run: |
        Compress-Archive -Path УчебныйГрафик_v1.0 -DestinationPath УчебныйГрафик_Windows.zip
      shell: pwsh

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: УчебныйГрафик_Windows.zip
        retention-days: 30

    - name: Upload exe separately
      uses: actions/upload-artifact@v4
      with:
        name: executable-only
        path: dist/УчебныйГрафик.exe
        retention-days: 30